"""Run an LLM-generated Playwright recorder for a DemoFlow session.

Usage:
    python scripts/record.py [<session_dir>]

Expects:
    <session_dir>/record-script.py   # generated by /demoflow:record

Behaviour:
    - Subprocess-runs the recorder with the session dir as cwd.
    - The generated recorder is responsible for launching Playwright with
      record_video_dir=. and writing the captured webm into the session dir
      as recording.webm (renaming Playwright's default if needed).
    - Verifies recording.webm appeared and reports its size and length.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from util import REQUIRED_PREP_KEYS, log, require_env, resolve_session


def probe_duration(path: Path) -> float | None:
    try:
        out = subprocess.check_output(
            [
                "ffprobe", "-v", "error",
                "-show_entries", "format=duration",
                "-of", "default=noprint_wrappers=1:nokey=1",
                str(path),
            ],
            stderr=subprocess.STDOUT,
        )
        return float(out.decode().strip())
    except Exception:
        return None


def main() -> int:
    session = resolve_session(sys.argv[1] if len(sys.argv) > 1 else None)
    require_env(REQUIRED_PREP_KEYS)

    recorder = session / "record-script.py"
    if not recorder.exists():
        sys.stderr.write(
            f"record-script.py not found in {session}. "
            "Run /demoflow:record to generate it.\n"
        )
        return 2

    log(f"Running recorder: {recorder}")
    result = subprocess.run(
        [sys.executable, str(recorder)],
        cwd=str(session),
    )
    if result.returncode != 0:
        log(f"Recorder exited with code {result.returncode}")
        return result.returncode

    out = session / "recording.webm"
    if not out.exists():
        sys.stderr.write(
            f"Expected {out} after recording, not found. "
            "Check record-script.py writes to recording.webm.\n"
        )
        return 1

    size_mb = out.stat().st_size / 1024 / 1024
    dur = probe_duration(out)
    log(f"Recording OK: {out.name} ({size_mb:.1f} MB" + (f", {dur:.1f}s)" if dur else ")"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
