"""Run an LLM-generated Playwright seeder for a DemoFlow session.

Usage:
    python scripts/seed.py [<session_dir>]

Expects:
    <session_dir>/seed-script.py   # generated by /demoflow:prep
    <session_dir>/plan.json        # serialised DemoFlow Context Block

Behaviour:
    - Validates required .env vars exist (DEMOFLOW_APP_URL, USERNAME, PASSWORD).
    - Runs seed-script.py as a subprocess in the session dir as cwd.
    - Streams the seeder's stdout/stderr live.
    - Reports outcome and any screenshots written under screenshots/.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from util import REQUIRED_PREP_KEYS, log, require_env, resolve_session


def main() -> int:
    session = resolve_session(sys.argv[1] if len(sys.argv) > 1 else None)
    require_env(REQUIRED_PREP_KEYS)

    seeder = session / "seed-script.py"
    if not seeder.exists():
        sys.stderr.write(
            f"seed-script.py not found in {session}. "
            "Run /demoflow:prep to generate it.\n"
        )
        return 2

    log(f"Running seeder: {seeder}")
    result = subprocess.run(
        [sys.executable, str(seeder)],
        cwd=str(session),
    )
    if result.returncode != 0:
        log(f"Seeder exited with code {result.returncode}")
        return result.returncode

    shots = sorted((session / "screenshots").glob("*.png"))
    log(f"Seeder OK. {len(shots)} screenshot(s) written:")
    for s in shots:
        log(f"  {s.relative_to(session.parent.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
